title: NumEconCopenhagen
urls: 
  - title: "Home"
    icon: "home"
    url: "/"
    weight: 5
  - title: "Guides"
    icon: "info"
    url: "/guides"
    weight: 10
  - title: "Lectures"
    icon: "assignment"
    url: "/lectures/"
    weight: 15
  - title: "Exercises"
    icon: "assignment"
    url: "/exercises/"
    weight: 20
  - title: "Course Plan"
    icon: "calendar_today"
    url: "/course-plan"
    weight: 25
  - title: "Self-study"
    icon: "school"
    url: "/self-study"
    weight: 30
  - title: "NumEcon"
    icon: "explore"
    url: "/numecon"
    weight: 35
  - title: "ConSav"
    icon: "code"
    url: "/consav"
    weight: 40

notebook:

  - path: "/exercises/"
    notebooks:
      - owner: "NumEconCopenhagen"
        repository: "exercises-2020"
        path: "PS1/problem_set_1.ipynb"
      - owner: "NumEconCopenhagen"
        repository: "exercises-2020"
        path: "PS2/problem_set_2.ipynb"
      - owner: "NumEconCopenhagen"
        repository: "exercises-2020"
        path: "PS3/problem_set_3.ipynb"
      - owner: "NumEconCopenhagen"
        repository: "exercises-2020"
        path: "PS4/problem_set_4.ipynb"
      - owner: "NumEconCopenhagen"
        repository: "exercises-2020"
        path: "PS5/problem_set_5.ipynb"
      - owner: "NumEconCopenhagen"
        repository: "exercises-2020"
        path: "PS6/problem_set_6.ipynb"
      - owner: "NumEconCopenhagen"
        repository: "exercises-2020"
        path: "PS7/problem_set_7.ipynb"
      - owner: "NumEconCopenhagen"
        repository: "lectures-2020"
        path: "exam/exam_2019.ipynb"
      - owner: "NumEconCopenhagen"
        repository: "lectures-2020"
        path: "exam/solution_2019.ipynb"

  - path: "/lectures/"
    notebooks:

      - owner: "NumEconCopenhagen"
        repository: "lectures-2020"
        path: "web/01/Introduction.ipynb"
      - owner: "NumEconCopenhagen"
        repository: "lectures-2020"
        path: "web/02/Primitives.ipynb"
      - owner: "NumEconCopenhagen"
        repository: "lectures-2020"
        path: "web/03/Optimize_print_and_plot.ipynb"
      - owner: "NumEconCopenhagen"
        repository: "lectures-2020"
        path: "web/04/Random_numbers_and_simulation.ipynb"
      - owner: "NumEconCopenhagen"
        repository: "lectures-2020"
        path: "web/05/Workflow_and_debugging.ipynb"
      - owner: "NumEconCopenhagen"
        repository: "lectures-2020"
        path: "web/06/Recap_and_overview.ipynb"
      - owner: "NumEconCopenhagen"
        repository: "lectures-2020"
        path: "web/07/Load_save_and_structure_data.ipynb"
      - owner: "NumEconCopenhagen"
        repository: "lectures-2020"
        path: "web/08/Basic_data_analysis.ipynb"
      - owner: "NumEconCopenhagen"
        repository: "lectures-2020"
        path: "web/09/Searching_and_sorting.ipynb"
      - owner: "NumEconCopenhagen"
        repository: "lectures-2020"
        path: "web/10/Solving_equations.ipynb"
      - owner: "NumEconCopenhagen"
        repository: "lectures-2020"
        path: "web/11/Numerical_optimization.ipynb"
      - owner: "NumEconCopenhagen"
        repository: "lectures-2020"
        path: "web/12/The_need_for_speed.ipynb"
      - owner: "NumEconCopenhagen"
        repository: "lectures-2020"
        path: "web/13/Other_programming_languages.ipynb"

  - path: "/numecon/"
    notebooks:
      - owner: "NumEconCopenhagen"
        repository: "NumEconNotebooks"
        path: "macro/ASAD.ipynb"
      - owner: "NumEconCopenhagen"
        repository: "NumEconNotebooks"
        path: "macro/OLG.ipynb"
      - owner: "NumEconCopenhagen"
        repository: "NumEconNotebooks"
        path: "macro/Ramsey.ipynb"
      - owner: "NumEconCopenhagen"
        repository: "NumEconNotebooks"
        path: "macro/Solow.ipynb"
      - owner: "NumEconCopenhagen"
        repository: "NumEconNotebooks"
        path: "micro/01_Budgetset.ipynb"
      - owner: "NumEconCopenhagen"
        repository: "NumEconNotebooks"
        path: "micro/02_Preferences.ipynb"
      - owner: "NumEconCopenhagen"
        repository: "NumEconNotebooks"
        path: "micro/03_Utility_maximization.ipynb"
      - owner: "NumEconCopenhagen"
        repository: "NumEconNotebooks"
        path: "micro/04_Substitution_income_and_wealth_effects.ipynb"
      - owner: "NumEconCopenhagen"
        repository: "NumEconNotebooks"
        path: "micro/05_Edgeworth.ipynb"
      - owner: "NumEconCopenhagen"
        repository: "NumEconNotebooks"
        path: "micro/06_Profit_maximization.ipynb"
      - owner: "NumEconCopenhagen"
        repository: "NumEconNotebooks"
        path: "micro/07_Partial_equilibrium.ipynb"
      - owner: "NumEconCopenhagen"
        repository: "NumEconNotebooks"
        path: "micro/08_Koopman.ipynb"
      - owner: "NumEconCopenhagen"
        repository: "NumEconNotebooks"
        path: "probability_theory/01_Stochastic_variables.ipynb"
      - owner: "NumEconCopenhagen"
        repository: "NumEconNotebooks"
        path: "probability_theory/02_Conditional_probability.ipynb"
