title: NUMECONCOPENHAGEN
urls: 
  - title: "Home"
    icon: "home"
    url: "/"
    weight: 5
  - title: "Guides"
    icon: "info"
    url: "/guides"
    weight: 10
  - title: "Lectures"
    icon: "assignment"
    url: "/lectures/"
    weight: 15
  - title: "Exercises"
    icon: "assignment"
    url: "/exercises/"
    weight: 20
  - title: "Course Plan"
    icon: "calendar_today"
    url: "/course-plan"
    weight: 25
  - title: "Self-study"
    icon: "school"
    url: "/self-study"
    weight: 30
  
notebook:
  - path: "/exercises/"
    notebooks:
      - owner: "numeconcopenhagen"
        repository: "lectures-2019"
        path: "02/Primitives.ipynb"
  - path: "/lectures/"
    notebooks:
      - owner: "numeconcopenhagen"
        repository: "lectures-2019"
        path: "01/Introduction.ipynb"
      - owner: "numeconcopenhagen"
        repository: "lectures-2019"
        path: "02/Primitives.ipynb"
      - owner: "numeconcopenhagen"
        repository: "lectures-2019"
        path: "03/Optimize_Print_and_Plot.ipynb"
      - owner: "numeconcopenhagen"
        repository: "lectures-2019"
        path: "04/Random_Numbers_and_Simulation.ipynb"
      - owner: "numeconcopenhagen"
        repository: "lectures-2019"
        path: "05/Workflow_and_debugging.ipynb"
      - owner: "numeconcopenhagen"
        repository: "lectures-2019"
        path: "06/Load_save_and_structure_data.ipynb"
      - owner: "numeconcopenhagen"
        repository: "lectures-2019"
        path: "07/Basic_data_analysis.ipynb"
      - owner: "numeconcopenhagen"
        repository: "lectures-2019"
        path: "07/Fun_applications.ipynb"
      - owner: "numeconcopenhagen"
        repository: "lectures-2019"
        path: "08/Searching_and_sorting.ipynb"
      - owner: "numeconcopenhagen"
        repository: "lectures-2019"
        path: "09/Solving_equations.ipynb"
      - owner: "numeconcopenhagen"
        repository: "lectures-2019"
        path: "10/Numerical_optimization.ipynb"
      - owner: "numeconcopenhagen"
        repository: "lectures-2019"
        path: "11/The_Need_for_Speed.ipynb"
      - owner: "numeconcopenhagen"
        repository: "lectures-2019"
        path: "12/SMD.ipynb"